version: '3.9'
services:
  app:
    build: ./
    container_name: chatbot-app
    ports:
      - 3000:3000
      - 3001:3001
    platform: linux/x86_64
    volumes:
      - ./app/backend:/app/backend
      - ./app/frontend:/app/frontend
    working_dir: /app
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: sh
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    container_name: chatbot-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 33060:3306